apiVersion: v1
kind: Secret
metadata:
    name: ms-secret
type: Opaque
data:
    jwt_secret: ZGV2LXNlY3JldC1zaWduaW5n  # echo -n 'dev-secret-signing' | base64
    mysql_password: YXBwX3Bhc3M=          # echo -n 'app_pass' | base64
