logging:
    config: classpath:logback-spring.xml
    level:
        root: INFO
        org.hibernate.SQL: OFF
        org.springframework.boot.autoconfigure: WARN
        org.springframework.web: INFO
        org.springframework.web.servlet.DispatcherServlet: OFF
        org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLogger: OFF
